//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-U14DSOG\\SA;Initial Catalog=QLLaoDong;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=tu1toi9A")]
        public string QLLaoDongConnectionString {
            get {
                return ((string)(this["QLLaoDongConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-U14DSOG\\SA;Initial Catalog=QuanLyLaoDong;Persist Security Inf" +
            "o=True;User ID=sa;Password=tu1toi9A")]
        public string QuanLyLaoDongConnectionString {
            get {
                return ((string)(this["QuanLyLaoDongConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-U14DSOG\\SA;Initial Catalog=QuanLyLaoDong;User ID=sa;Password=" +
            "tu1toi9A")]
        public string QuanLyLaoDongConnectionString1 {
            get {
                return ((string)(this["QuanLyLaoDongConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-U14DSOG\\SA;Initial Catalog=QLLaoDong;User ID=sa;Password=tu1t" +
            "oi9A")]
        public string QLLaoDongConnectionString1 {
            get {
                return ((string)(this["QLLaoDongConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-S8DEDHP\\SQLEXPRESS;Initial Catalog=QLLaoDong;Integrated Secur" +
            "ity=True")]
        public string QLLaoDongConnectionString2 {
            get {
                return ((string)(this["QLLaoDongConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-U14DSOG\\SA;Initial Catalog=QLyLaoDong;User ID=sa;Password=tu1" +
            "toi9A")]
        public string QLyLaoDongConnectionString {
            get {
                return ((string)(this["QLyLaoDongConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-U14DSOG\\SA;Initial Catalog=QLyLaoDong;Persist Security Info=T" +
            "rue;User ID=sa;Password=tu1toi9A")]
        public string QLLaoDongConnectionString3 {
            get {
                return ((string)(this["QLLaoDongConnectionString3"]));
            }
        }
    }
}
